name: snake

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: K4BOTELHO
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Verifica arquivos gerados
        run: ls -la dist

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
